//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMe.Server.PlayMeCallbackServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayMeCallbackServiceReference.ISpotifyCallbackService")]
    public interface ISpotifyCallbackService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpotifyCallbackService/PlayingTrackChanged")]
        void PlayingTrackChanged(PlayMe.Common.Model.QueuedTrack track);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpotifyCallbackService/QueueChanged")]
        void QueueChanged(System.Collections.Generic.List<PlayMe.Common.Model.QueuedTrack> queue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpotifyCallbackService/TrackHistoryChanged")]
        void TrackHistoryChanged(PlayMe.Common.Model.PagedResult<PlayMe.Common.Model.QueuedTrack> history);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpotifyCallbackServiceChannel : PlayMe.Server.PlayMeCallbackServiceReference.ISpotifyCallbackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpotifyCallbackServiceClient : System.ServiceModel.ClientBase<PlayMe.Server.PlayMeCallbackServiceReference.ISpotifyCallbackService>, PlayMe.Server.PlayMeCallbackServiceReference.ISpotifyCallbackService {
        
        public SpotifyCallbackServiceClient() {
        }
        
        public SpotifyCallbackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpotifyCallbackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpotifyCallbackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpotifyCallbackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PlayingTrackChanged(PlayMe.Common.Model.QueuedTrack track) {
            base.Channel.PlayingTrackChanged(track);
        }
        
        public void QueueChanged(System.Collections.Generic.List<PlayMe.Common.Model.QueuedTrack> queue) {
            base.Channel.QueueChanged(queue);
        }
        
        public void TrackHistoryChanged(PlayMe.Common.Model.PagedResult<PlayMe.Common.Model.QueuedTrack> history) {
            base.Channel.TrackHistoryChanged(history);
        }
    }
}
